version: "3"

services:
  app:
    build: .
    container_name: grpc_challenge_app
    ports:
      - "50051:50051"
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  sqlite-db:
    image: bitnami/sqlite:latest
    container_name: my_sqlite_db
    restart: always
    volumes:
      - ./sqlite-data:/bitnami/sqlite